package models

type Leads struct {
	ID                   int    `json:"id"`
	FirstName            string `json:"firstName"`
	LastName             string `json:"lastName"`
	Updated              string `json:"updated"`
	LastLoginDate        string `json:"lastLoginDate"`
	LeadGuid             string `json:"leadGuid"`
	Country              string `json:"country"`
	City                 string `json:"city"`
	TimeZone             string `json:"timeZone"`
	SalesStatus          string `json:"salesStatus"`
	Language             string `json:"language"`
	BusinessUnit         string `json:"businessUnit"`
	DomainName           string `json:"domainName"`
	IsQualified          bool   `json:"isQualified"`
	ConversionAgentID    int    `json:"conversionAgentId"`
	RetentionManagerID   int    `json:"retentionManagerId"`
	VIPManagerID         int    `json:"vipManagerId"`
	CloserManagerID      int    `json:"closerManagerId"`
	ConversionAgentTeam  string `json:"conversionAgentTeam"`
	RetentionManagerTeam string `json:"retentionManagerTeam"`
	VIPManagerTeam       string `json:"vipManagerTeam"`
	CloserManagerTeam    string `json:"closerManagerTeam"`
	AffiliateID          string `json:"affiliateId"`
	AffiliateName        string `json:"affiliateName"`
	UTMCampaign          string `json:"utmCampaign"`
	UTMMedium            string `json:"utmMedium"`
	UTMSource            string `json:"utmSource"`
	UTMTerm              string `json:"utmTerm"`
	ReferringPage        string `json:"referringPage"`
	RegistrationDate     string `json:"registrationDate"`
	AccountCreationDate  string `json:"accountCreationDate"`
	ActivationDate       string `json:"activationDate"`
	FullyActivationDate  string `json:"fullyActivationDate"`
	SubChannel           string `json:"subChannel"`
	ChannelName          string `json:"channelName"`
	TLName               string `json:"tlName"`
	TrackingLinkID       string `json:"trackingLinkId"`
	Deposited            bool   `json:"deposited"`
	OriginalLeadID       int    `json:"originalLeadId"`
	OriginalByNameLeadID int    `json:"originalByNameLeadId"`
	NameDuplicates       string `json:"nameDuplicates"`
	Email                string `json:"email"`
	OfferDescription     string `json:"offerDescription"`
	IPAddress            string `json:"ipAddress"`
	LandingPage          string `json:"landingPage"`
}
