import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar/app-sidebar";
import { Navbar } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <SidebarProvider>
          <main className="flex flex-col w-full">
            <div className="flex">
              <AppSidebar />

              <div className="flex flex-col w-full">
                <Navbar />
                <div className="w-full h-max overflow-auto overflow p-2 pb-5">
                  {children}
                </div>
              </div>
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
